version: '3.8'

services:
  postgres:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PG_USER} -d ${DB}"]
      interval: 5s
      retries: 10

  db-migrate:
    image: flyway/flyway:10
    command: -baselineOnMigrate=true migrate
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./migrations:/flyway/sql
    environment:
      FLYWAY_URL: jdbc:postgresql://postgres:5432/${DB}
      FLYWAY_USER: ${PG_USER}
      FLYWAY_PASSWORD: ${PG_PASSWORD}

  worker-bot:
    build:
      context: .
      dockerfile: ./src/ArticlesAggregator.Worker/Dockerfile
    depends_on:
      db-migrate:
        condition: service_completed_successfully
    env_file: .env

  external-parser:
    image: konbigog/webapi
    platform: linux/amd64
    ports:
      - "8080:8080"
    command: go run cmd/webapi/main.go
volumes:
  pgdata:
